CREATE DATABASE IF NOT EXISTS hibernate;
USE hibernate;

CREATE TABLE IF NOT EXISTS HIBERNATE_DEVELOPERS
(
   ID INT NOT NULL AUTO_INCREMENT,
   FIRST_NAME VARCHAR(50) DEFAULT NULL,
   LAST_NAME VARCHAR(50) DEFAULT NULL,
   SPECIALTY VARCHAR(50) DEFAULT NULL,
   EXPERIENCE INT DEFAULT NULL,
   PRIMARY KEY(ID)
);